### ISSUE TITLE
Error trying to runApp

### ISSUE THREAD

**Issue by ValorZard** [wgpu4k/hello-cube#5]
```PS C:\Github\hello-cube> .\gradlew runApp
Downloading https://services.gradle.org/distributions/gradle-8.8-bin.zip
.............10%.............20%.............30%.............40%.............50%.............60%..............70%.............80%.............90%.............100%

Welcome to Gradle 8.8!

Here are the highlights of this release:
 - Running Gradle on Java 22
 - Configurable Gradle daemon JVM
 - Improved IDE performance for large projects

For more details see https://docs.gradle.org/8.8/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
w: New 'wasm' target is Work-in-Progress and is subject to change without notice. Please report encountered issues to https://kotl.in/issue


> Task :runApp FAILED
will extract library to path C:\Program Files\Java\jdk-22\bin\WGPU0.dll
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files\Java\jdk-22\bin\WGPU0.dll
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
        at java.base/java.nio.file.Files.copy(Files.java:3145)
        at io.ygdrasil.wgpu.internal.jvm.LibraryLoaderKt.extractResourceToTemp(LibraryLoader.kt:95)
        at io.ygdrasil.wgpu.internal.jvm.LibraryLoaderKt.exportAndLoadLibrary(LibraryLoader.kt:14)
        at io.ygdrasil.wgpu.WGPU$Companion.loadLibrary(WGPU.kt:113)
        at MainKt$main$1.invokeSuspend(main.kt:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at MainKt.main(main.kt:11)
        at MainKt.main(main.kt)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runApp'.
> Process 'command 'C:\Program Files\Java\jdk-22\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 50s
2 actionable tasks: 2 executed```

**Comment by ygdrasil-io** [comment]
related to https://github.com/wgpu4k/wgpu4k/issues/22 will be fixe on next preview.

**Comment by ygdrasil-io** [comment]
Should be fix now, please reopen if you reproduce it again on this repository.
